#!/bin/sh

check_set()
{
	if ! test -n "$1" ; then
		echo "test variable '$1' must be set"
		exit 1
	fi
}

check_set "NAME"
check_set "PCAPS"
check_set "OUTPUT"
if ! test -r "$srcdir/$OUTPUT" ; then
	echo "Cannot read test output file ($OUTPUT)"
	exit 1
fi

if test -z "$PLUGIN" ; then
	PLUGIN="../plugins/dumper/.libs/dumper.so"
fi

output="${OUTPUT}2"
log="${OUTPUT%%.*}.log"
rm -f "$output" "$log"

for pcap in $PCAPS ; do
	echo "-- $pcap --" | tee -a "$output"
    ../src/junkie -p "$PLUGIN" -l "$log" -e '(set-log-level log-debug)(set-log-level log-warning "redim_array")(set-log-level log-warning "mutex")' -e "$CMDLINE" -r "$srcdir/$pcap" | filter >> "$output"
done

if ! diff "$srcdir/$OUTPUT" "$output"; then
	echo "Output differ from $OUTPUT ! (see actual output in $output)"
	exit 1
else
    rm -f "$output" "$log"
fi

