#!/bin/sh

set -e

junkie="../src/junkie"
nark="../src/nark"

if ! test -x $junkie || ! test -x $nark ; then
    echo "Missing executable $junkie or $nark"
    exit 1
fi

if ! test -n "$(which stdbuf)" ; then
	echo "!!WARNING!! You need stdbuf (in recent coreutils) to run this test !!WARNING!!"
	exit 0
fi

echo "Testing serialization"

dumplog="serialize_check.dump"
narklog="serialize_check.nark"

rm -f $dumplog $narklog

stdbuf -oL $nark > $narklog &
narkpid=$!
disown $narkpid

# FIXME: It may happen that one pcap is finished while the for-each-file-in is not over yet, thus quitting junkie before all pcaps have been played.
$junkie > $dumplog \
        -p ../plugins/dumper/.libs/dumper.so \
        -p ../plugins/serializer/.libs/serializer.so \
        -e '(for-each-file-in "pcap" (lambda (sub) (for-each-file-in sub open-pcap)))'

kill $narkpid

if diff $dumplog $narklog > /dev/null ; then
	rm -f $dumplog $narklog
	exit 0
else
	echo "Output differs! See $dumplog and $narklog for details."
	exit 1
fi
