#!/bin/sh
# vim:sw=4 ts=4 sts=4 expandtab

set -e

junkie="../src/junkie"

if ! test -x $junkie ; then
    echo "Missing executable $junkie"
    exit 1
fi

echo "Testing serialization"

serlog="serialize_check.ser"
deserlog="serialize_check.deser"

rm -f $serlog $deserlog

echo "Running deserializer"
$junkie > $deserlog \
    -e '(open-deserializer)' \
    -p ../plugins/dumper/.libs/dumper.so &
deserpid=$!
#disown $deserpid
sleep 1 # wait for junkie to be ready

echo "Running serializer"
$junkie > $serlog \
        -p ../plugins/dumper/.libs/dumper.so \
        -p ../plugins/serializer/.libs/serializer.so \
        -e '(set-quit-when-done #f)' \
        -e '(for-each-file-in "'"$srcdir"'/pcap" (lambda (sub) (for-each-file-in sub open-pcap)))' \
        -e '(sleep 1)' \
        -e '(exit)' || true

sleep 1 # wait for junkie to print everything
echo "Killing deserializer"
kill $deserpid

if diff $serlog $deserlog > /dev/null ; then
    rm -f $serlog $deserlog
    exit 0
else
    echo "Output differs! See $serlog and $deserlog for details."
    exit 1
fi

