#!/bin/sh
# vim:sw=4 ts=4 sts=4 expandtab

set -e

junkie="../src/junkie"
nark="../src/nark"

if ! test -x $junkie || ! test -x $nark ; then
    echo "Missing executable $junkie or $nark"
    exit 1
fi

if ! test -n "$(which stdbuf)" ; then
    echo "!!WARNING!! You need stdbuf (in recent coreutils) to run this test !!WARNING!!"
    exit 0
fi

echo "Testing serialization"

dumplog="serialize_check.dump"
narklog="serialize_check.nark"

rm -f $dumplog $narklog

echo "Running nark"
stdbuf -oL $nark > $narklog &
narkpid=$!
#disown $narkpid
sleep 1 # wait for nark to be ready

echo "Running junkie"
$junkie > $dumplog \
        -p ../plugins/dumper/.libs/dumper.so \
        -p ../plugins/serializer/.libs/serializer.so \
        -e '(set-quit-when-done #f)' \
        -e '(for-each-file-in "pcap" (lambda (sub) (for-each-file-in sub open-pcap)))' \
        -e '(exit)' || true

echo "Killing nark"
sleep 1 # wait for nark to print everything
kill $narkpid

if diff $dumplog $narklog > /dev/null ; then
    rm -f $dumplog $narklog
    exit 0
else
    echo "Output differs! See $dumplog and $narklog for details."
    exit 1
fi
