// -*- c-basic-offset: 4; c-backslash-column: 79; indent-tabs-mode: nil -*-
// vim:sw=4 ts=4 sts=4 expandtab
#ifndef CIFS_H_101221
#define CIFS_H_101221
#include <junkie/proto/proto.h>

/** @file
 * @brief CIFS informations
 */

extern struct proto *proto_cifs;

enum smb_command {
    SMB_COM_CREATE_DIRECTORY        = 0x00,
    SMB_COM_DELETE_DIRECTORY,
    SMB_COM_OPEN,
    SMB_COM_CREATE,
    SMB_COM_CLOSE,
    SMB_COM_FLUSH,
    SMB_COM_DELETE,
    SMB_COM_RENAME,
    SMB_COM_QUERY_INFORMATION,
    SMB_COM_SET_INFORMATION,
    SMB_COM_READ_INFORMATION,
    SMB_COM_WRITE_INFORMATION,
    SMB_COM_LOCK_BYTE_RANGE,
    SMB_COM_UNLOCK_BYTE_RANGE,
    SMB_COM_CREATE_TEMPORARY,
    SMB_COM_CREATE_NEW,
    SMB_COM_CHECK_DIRECTORY,
    SMB_COM_PROCESS_EXIT,
    SMB_COM_SEEK,
    SMB_COM_LOCK_AND_READ,
    SMB_COM_WRITE_AND_UNLOCK,

    SMB_COM_READ_RAW                = 0x1a,
    SMB_COM_READ_MPX,
    SMB_COM_READ_MPX_SECONDARY,
    SMB_COM_WRITE_RAW,
    SMB_COM_WRITE_MPX,
    SMB_COM_WRITE_MPX_SECONDARY,
    SMB_COM_WRITE_COMPLETE,
    SMB_COM_QUERY_SERVER,
    SMB_COM_SET_INFORMATION2,
    SMB_COM_QUERY_INFORMATION2,
    SMB_COM_LOCKING_ANDX,
    SMB_COM_TRANSACTION,
    SMB_COM_TRANSACTION_SECONDARY,
    SMB_COM_IOCTL,
    SMB_COM_IOCTL_SECONDARY,
    SMB_COM_COPY,
    SMB_COM_MOVE,
    SMB_COM_ECHO,
    SMB_COM_WRITE_AND_CLOSE,
    SMB_COM_OPEN_ANDX,
    SMB_COM_READ_ANDX,
    SMB_COM_WRITE_ANDX,
    SMB_COM_NEW_FILE_SIZE,
    SMB_COM_CLOSE_AND_TREE_DISC,
    SMB_COM_TRANSACTION2,
    SMB_COM_TRANSACTION2_SECONDARY,
    SMB_COM_FIND_CLOSE2,
    SMB_COM_FIND_NOTIFY_CLOSE,

    SMB_COM_TREE_CONNECT            = 0x70,
    SMB_COM_TREE_DISCONNECT,
    SMB_COM_NEGOCIATE,
    SMB_COM_SESSION_SETUP_ANDX,
    SMB_COM_LOGOFF_ANDX             = 0x75,

    SMB_COM_SECURITY_PACKAGE_ANDX   = 0x7e,
    SMB_COM_QUERY_INFORMATION_DISK  = 0x80,
    SMB_COM_SEARCH,
    SMB_COM_FIND,
    SMB_COM_FIND_UNIQUE,
    SMB_COM_FIND_CLOSE              = 0x84,
    SMB_COM_NT_TRANSACT             = 0xa0,
    SMB_COM_NT_TRANSACT_SECONDARY,
    SMB_COM_NT_CREATE_ANDX,
    SMB_COM_NT_CANCEL               = 0xa4,
    SMB_COM_NT_RENAME,
    SMB_COM_OPEN_PRINT_FILE         = 0xc0,
    SMB_COM_WRITE_PRINT_FILE,
    SMB_COM_CLOSE_PRINT_FILE,
    SMB_COM_GET_PRINT_FILE,
    SMB_COM_READ_BULK               = 0xd8,
    SMB_COM_WRITE_BULK,
    SMB_COM_WRITE_BULK_DATA,
    SMB_COM_INVALID                 = 0xfe,
    SMB_COM_NO_ANDX_COMMAND
};

struct cifs_proto_info {
    struct proto_info info;
    enum smb_command command;
    uint32_t status;

#define   SMB_DOMAIN   0x0001
#define   SMB_USER     0x0002
    unsigned set_values;
    char domain[50];
    char user[50];
};

void cifs_init(void);
void cifs_fini(void);

#endif
