// -*- c-basic-offset: 4; c-backslash-column: 79; indent-tabs-mode: nil -*-
// vim:sw=4 ts=4 sts=4 expandtab
#ifndef SKINNY_H_130515
#define SKINNY_H_130515
#include <junkie/proto/proto.h>

/** @file
 * @brief Skinny informations
 */

extern struct proto *proto_skinny;

// Message Ids

enum skinny_msgid {
    SKINNY_KEEPALIVE,
    SKINNY_REGISTER,
    SKINNY_IP_PORT,
    SKINNY_KEY_PAD_BUTTON,
    SKINNY_ENBLOC_CALL,
    SKINNY_STIMULUS,
    SKINNY_OFF_HOOK,
    SKINNY_ON_HOOK,
    SKINNY_HOOK_FLASH,
    SKINNY_FORWARD_STATUS_REQ,
    SKINNY_SPEED_DIAL_STATUS_REQ,
    SKINNY_LINE_STATUS_REQ,
    SKINNY_CONFIGURATION_STATUS_REQ,
    SKINNY_TIME_DATE_REQ,
    SKINNY_BUTTON_TEMPLATE_REQ,
    SKINNY_VERSION_REQ,
    SKINNY_CAPABILITIES_RESPONSE,
    // gap here (and more to follow)
    SKINNY_MEDIA_PORT_LIST = 0x0011,
    SKINNY_SERVER_REQ = 0X0012,
    SKINNY_ALARM = 0X0020,
    SKINNY_MULTICAST_MEDIA_RECEPT_ACK = 0X0021,
    SKINNY_OFF_HOOK_WITH_CALLING_PARTY_NUMBER = 0X0024,
    SKINNY_OPEN_RECEIVE_CHANNEL_ACK = 0X0022,
    SKINNY_CONNECTION_STATISTICS_RESPONSE = 0X0023,
    SKINNY_SOFT_KEY_TEMPLATE_REQ = 0X0025,
    SKINNY_SOFT_KEY_SET_REQ = 0X0026,
    SKINNY_SOFT_KEY_EVENT = 0X0027,
    SKINNY_UNREGISTER = 0X0028,
    SKINNY_KEEP_ALIVE = 0X0081,
    SKINNY_START_TONE = 0X0082,
    SKINNY_STOP_TONE = 0X0083,
    SKINNY_SET_RINGER = 0X0085,
    SKINNY_SET_LAMP = 0X0086,
    SKINNY_SET_HOOK_FLASH_DETECT = 0X0087,
    SKINNY_SET_SPEAKER_MODE = 0X0088,
    SKINNY_SET_MICROPHONE_MODE = 0X0089,
    SKINNY_START_MEDIA_TRANSMIT = 0X008A,
    SKINNY_STOP_MEDIA_TRANSMIT = 0X008B,
    SKINNY_CALL_INFORMATION = 0X008F,
    SKINNY_REGISTER_REJECT = 0X009D,
    SKINNY_RESET = 0X009F,
    SKINNY_FORWARD_STATUS = 0X0090,
    SKINNY_SPEED_DIAL_STATUS = 0X0091,
    SKINNY_LINE_STATUS = 0X0092,
    SKINNY_CONFIGURATION_STATUS = 0X0093,
    SKINNY_DEFINE_TIME_N_DATE = 0X0094,
    SKINNY_START_SESSION_TRANSMIT = 0X0095,
    SKINNY_STOP_SESSION_TRANSMIT = 0X0096,
    SKINNY_BUTTON_TEMPLATE = 0X0097,
    SKINNY_VERSION = 0X0098,
    SKINNY_DISPLAY_TEXT = 0X0099,
    SKINNY_CLEAR_DISPLAY = 0X009A,
    SKINNY_CAPABILITIES_REQ = 0X009B,
    SKINNY_ENUNCIATOR_COMMAND = 0X009C,
    SKINNY_SERVER_RESP = 0X009E,
    SKINNY_START_MULTICAST_MEDIA_RECEPT = 0X0101,
    SKINNY_START_MULTICAST_MEDIA_TRANSMIT = 0X0102,
    SKINNY_STOP_MULTICAST_MEDIA_RECEPT = 0X0103,
    SKINNY_STOP_MULTICAST_MEDIA_TRANSMIT = 0X0104,
    SKINNY_OPEN_RECEIVE_CHANNEL = 0X0105,
    SKINNY_CLOSE_RECEIVE_CHANNEL = 0X0106,
    SKINNY_CONNECTION_STATISTICS_REQ = 0X0107,
    SKINNY_SOFT_KEY_TEMPLATE_RESP = 0X0108,
    SKINNY_SOFT_KEY_SET_RESP = 0X0109,
    SKINNY_SELECT_SOFT_KEYS = 0X0110,
    SKINNY_CALL_STATE = 0X0111,
    SKINNY_DISPLAY_PROMPT = 0X0112,
    SKINNY_CLEAR_PROMPT = 0X0113,
    SKINNY_DISPLAY_NOTIFY = 0X0114,
    SKINNY_CLEAR_NOTIFY = 0X0115,
    SKINNY_ACTIVATE_CALL_PLANE = 0X0116,
    SKINNY_DEACTIVATE_CALL_PLANE = 0X0117,
    SKINNY_UNREGISTER_ACK = 0X0118,
};

/// SKINNY message
struct skinny_proto_info {
    struct proto_info info;
    enum skinny_msgid msgid;
};

void skinny_init(void);
void skinny_fini(void);

#endif
